# (c) 2024 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.
# This AWS Content is provided subject to the terms of the AWS Customer Agreement
# available at http://aws.amazon.com/agreement or other written agreement between
# Customer and Amazon Web Services, Inc.

version: 0.2

phases:
  build:
    commands:
       - echo "CDK Prerequisites Stage"
       - echo $AWS_ACCOUNT_ID
       - cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_DEFAULT_REGION
       - aws emr create-default-roles