# (c) 2024 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.
# This AWS Content is provided subject to the terms of the AWS Customer Agreement
# available at http://aws.amazon.com/agreement or other written agreement between
# Customer and Amazon Web Services, Inc.

version: 0.2

phases:
  build:
    commands:
      - JAVA_11=$(alternatives --display java | grep 'family java-11-openjdk' | cut -d' ' -f1)
      - export JAVA_HOME=$(alternatives --display jre_11 | grep 'family' | cut -d' ' -f1)
      - alternatives --set java $JAVA_11
      - APPLICATION_PREFIX=`grep lambdaprefix.paramvalue ./$APPLICATION/environments/$ENVIRONMENT/cdk.properties | awk -F= '{print $2}'`
      - STACK_PREFIX=`grep cdac.entities.paramvalue ./$APPLICATION/environments/$ENVIRONMENT/cdk.properties | awk -F= '{print $2}'`
      - echo "APPLICATION_PREFIX=$APPLICATION_PREFIX" >> pipeline.env
      - echo "STACK_PREFIX=$STACK_PREFIX" >> pipeline.env
      - echo "JAVA_11=$JAVA_11" >> pipeline.env
      - echo "JAVA_HOME_11=$JAVA_HOME" >> pipeline.env
      - echo "APPLICATION_PREFIX=$APPLICATION_PREFIX"
      - echo "STACK_PREFIX=$STACK_PREFIX"
      - echo "STACK_PREFIX=$STACK_PREFIX-prerequisites"
      - echo "JAVA_11=$JAVA_11"
      - echo "JAVA_HOME_11=$JAVA_HOME"
      - echo "ENVIRONMENT=$ENVIRONMENT"
      - cd ./$APPLICATION
      - cdk deploy -c environment=$ENVIRONMENT $STACK_PREFIX-prerequisites
